title: Ying Xin Tan (Chris) # your name (or website title) here
logo: "/images/Official_Head_Circle_40%.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Monash University</strong><br>
  Mechatronics Engineering (AI Stream)<br>
  Fresh Graduate (Cohort of 2024)

  <br><br>
  <a href="https://www.linkedin.com/in/chris-tanyx/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
